INTEGER, PLUS, MINUS, EOF = 'INTEGER', 'PLUS', 'MINUS', 'EOF'
MULT, DIV = "MULT", "DIV"
LPARENT, RPARENT = "LPARENT", "RPARENT"
ID = "IDENTIFIER"
DOT, SEMI = "DOT", "SEMI"
ASSIGN = "ASSIGN"
BEGIN, END = "BEGIN", "END"
